/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as ChooseOrganizationRouteImport } from './routes/choose-organization'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as AppDocumentIndexRouteImport } from './routes/_app/document/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app/settings/organization'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseOrganizationRoute = ChooseOrganizationRouteImport.update({
  id: '/choose-organization',
  path: '/choose-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/auth/check-email',
  path: '/auth/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentIndexRoute = AppDocumentIndexRouteImport.update({
  id: '/document/',
  path: '/document/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/choose-organization': typeof ChooseOrganizationRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/document/': typeof AppDocumentIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/choose-organization': typeof ChooseOrganizationRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/': typeof AppIndexRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/document': typeof AppDocumentIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/choose-organization': typeof ChooseOrganizationRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/document/': typeof AppDocumentIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-organization'
    | '/onboarding'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/invitations/accept'
    | '/settings/organization'
    | '/api/auth/$'
    | '/document/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/choose-organization'
    | '/onboarding'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/invitations/accept'
    | '/'
    | '/settings/organization'
    | '/api/auth/$'
    | '/document'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/choose-organization'
    | '/onboarding'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/invitations/accept'
    | '/_app/'
    | '/_app/settings/organization'
    | '/api/auth/$'
    | '/_app/document/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ChooseOrganizationRoute: typeof ChooseOrganizationRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-organization': {
      id: '/choose-organization'
      path: '/choose-organization'
      fullPath: '/choose-organization'
      preLoaderRoute: typeof ChooseOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/auth/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/document/': {
      id: '/_app/document/'
      path: '/document'
      fullPath: '/document/'
      preLoaderRoute: typeof AppDocumentIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppDocumentIndexRoute: typeof AppDocumentIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppDocumentIndexRoute: AppDocumentIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ChooseOrganizationRoute: ChooseOrganizationRoute,
  OnboardingRoute: OnboardingRoute,
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
