/**
 * Fenr database schema barrel.
 *
 * This is the single source of truth handed to drizzle-kit for migrations
 * (see ../drizzle.config.ts). Auth tables are generated by the Better Auth
 * CLI into ../auth-schema.ts and re-exported here so they participate in
 * the same migration history as app tables.
 */
export * from "../auth-schema"
